### ISSUE TITLE
built from source on debian10 results in broken stimfit

### ISSUE THREAD

**Issue by schloegl** [neurodroid/stimfit#80] opened 2019-08-28 17:50 UTC
Trying to build stimfit from on debian 10, results in unusable stimfit.  

How to reproduce: 

```
	sudo apt build-dep stimfit 
	git clone https://github.com/neurodroid/stimfit.git
	cd stimfit
	./autogen.sh 
	./configure --with-biosiglite --with-pslope --enable-python 
	make -j 
	sudo make install 
```

starting stimfit, either with 
  `     ./stimfit `
or 
	`/usr/local/bin/stimfit `

results in opening a dialog "an assertion failed", 

`../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxCommandEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxNotifyEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxScrollEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxScrollWinEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxMouseEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxKeyEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxSizeEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxPaintEvent" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multip
...
`

until stimfit crashes with a segmentation fault 
 

When building without python, the problem does not occur

    `    make distclean && ./configure --with-biosiglite --with-pslope --disable-python && make -j
`

**Comment by neurodroid** [comment] 2019-08-29 10:58
Duplicate of issue #70 
Fixed by commits 166522a2 and d7ff280f that closed issue #70 and issue #71 
To reproduce, make sure you've installed `libwxgtk3.0-gtk3-dev` and set `--with-wx-config="wx-config --toolkit=gtk3"`

**Closed by neurodroid** 2019-08-29 10:58 UTC
